'use client'
import "../app/globals.css";
import StoreProvider from "./storeProvider";
import Navbar from "../components/Navbar";
import Sidebar from "../components/sideBar";
import { useState } from "react";

export const Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Navbar toggleSidebar={toggleSidebar} />
          <div className="flex">
            {isSidebarOpen && <Sidebar />}
            <main className={`flex-1 ${isSidebarOpen ? 'ml-64' : ''}`}>
              {children}
            </main>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
